### ISSUE TITLE
Manually deleting the "Make me Rich" TX puts the UI in a weird state

### ISSUE THREAD

**Issue by epheph** [DarkFlorist/TheInterceptor#102]
If you enable "Make me rich" it adds a tx to head of simulation stack

![Screenshot 2023-01-18 at 9 15 56](https://user-images.githubusercontent.com/361654/213245907-adb9e531-c67d-46e4-99b1-1c4c87f83bf9.png)

that TX is deletable. When deleted, the button is still "make me rich" but the tx is no longer present:
![Screenshot 2023-01-18 at 9 16 09](https://user-images.githubusercontent.com/361654/213246064-e531bd9d-5a7c-46e7-82aa-0d72f092401a.png)

**Comment by KillariDev** [comment]
What should it do instead? Should we just remove option to remove that transaction?

**Comment by MicahZoltu** [comment]
It seems like correctly unchecking the make-me-rich button would be a more appropriate solution?

**Comment by epheph** [comment]
Ya i think either is good. maybe unchecking is slightly better?

**Comment by KillariDev** [comment]
okay, let's change it so that it get's unchecked
