### ISSUE TITLE
Number expression uses decimals strangely (using k when not necessary)

### ISSUE THREAD

**Issue by epheph** [DarkFlorist/TheInterceptor#103]
For anything in the 1,000's range, it is strange to express `1,455` as `1.455k`

![Screenshot 2023-01-18 at 9 58 17](https://user-images.githubusercontent.com/361654/213246241-288cc4cc-a87d-41f1-bc16-37b48b4b2d8e.png)

**Comment by MicahZoltu** [comment]
What is the problem here?  You think it shouldn't switch to K after 1 but instead after some other value?  Should it also switch to M after something bigger than 1,000,000?

**Comment by epheph** [comment]
Right, you shouldn't get suffix's involved if the end result is larger than printing the exact number

**Comment by MicahZoltu** [comment]
So if we rounded to 1 decimal place you would be OK with `1.5k`?  What about if it is ~equal in length, so `1.46k`?

I have a preference for consistency of switching, even if it is a bit odd at the edges (like your example), but maybe we can come up with a strategy that is consistent and alleviates your concern.

**Comment by epheph** [comment]
I think the problem is that the "edge case" is by far the most common case. People are usually moving between 1,000 to 10,000 USDC, DAI, USDT, UNI, LINK, etc. 

i think if it's < 10,000 you just show the number ?

**Comment by KillariDev** [comment]
it's not intended necessary to be shorter, but clearer, so you don't need to count zeroes :) I think "1.51k" is more clear than "1510", but that's just me :)

**Comment by epheph** [comment]
what about 1.514k vs 1,514 ? it's a very minor issue for sure, not going to battle for it. if it's intentional, it doesn't bother me. feel free to wontfix

**Comment by KillariDev** [comment]
Well, In Finnish, comma is used as the decimal separator, so that's why I find it confusing when it's used as thousand's separator. I would prefer that we don't use commas for numbers, just dots. Space's would be fine too. Would "1 514" look more understandable?
