### ISSUE TITLE
Setting a label on an address from the switch address dialog doesn't update the address immediately.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#105]
1. Have an unlabeled address.
2. Go to a dapp such that the "do you want to give this dapp access to address X" popup appears.
3. Click the address label edit button to the right of the address.
4. Give the address a label.
5. Notice that the address is unlabeled in the popup still.
6. Go to other places in the UI and notice that the address is labeled.

**Comment by KillariDev** [comment]
yeah, metadata is not updated in popups after they have been created. I'll fix that when I modify them to not use global state anymore.
