### ISSUE TITLE
Clicking the label button should clear label and set focus.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#108]
Currently when you click the label button to add a label to an address you are showed a window with two fields that both contain an address, one of which is greyed out and neither of which has focus.  When the label editor is displayed, it should have the top field empty with placeholder text like "type name here" and the address field should not be underlined (so it doesn't look like an input box) and the address should be colored so it doesn't look like placeholder text.

**Comment by KillariDev** [comment]
ah, I agree its not clear enough
