### ISSUE TITLE
Add privatekey 0x1 as an default address and allow signing with it

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/TheInterceptor#117]
What would be a good name for such address?

**Comment by MicahZoltu** [comment]
Name suggestion: `DO NOT SEND ANY ETH TO THIS ADDRESS`

**Comment by KillariDev** [comment]
> Name suggestion: `DO NOT SEND ANYTHING TO THIS ADDRESS`

The problem with this name is, that it doesn't explain where you can use it for
