### ISSUE TITLE
`Make me rich` Button not working

### ISSUE THREAD

**Issue by ebulku** [DarkFlorist/TheInterceptor#1234]
I am trying to use it in Chrome, but nothing happens. I checked and unchecked several times also after restarting chrome. There is no console log errors or warnings. I will try to disable my other extensions later to check if there is any conflicts.

**Comment by KillariDev** [comment]
Hey, it should not show anything in the Ui that it's working. If its enabled, you should see your balance change in the website you are browsing. Eg, if you go to horswap ( https://2.horswap.eth.limo/#/swap ) you can see your eth balance: 
<img width="162" alt="image" src="https://github.com/user-attachments/assets/fd4ccbf9-93d6-4a06-a067-9cf7516c938d" />

In the older versions of the interceptor, we showed a transaction added to stack that showed that you are being made rich. This is no longer being done as the richness is achieved via other means

**Comment by ebulku** [comment]
Thank you for the detailed answer. Yes I can check now the balance, but somehow when I checked yesterday it was showing 0.
