### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by randomishwalk** [DarkFlorist/TheInterceptor#13]
Is this under MIT license? Couldn't find a LICENSE file in the repo but saw MIT mentioned elsewhere

**Comment by MicahZoltu** [comment]
We are internally discussing what license to use.  Likely MIT or Unlicense.  We didn't want to hold up making the code available on that, so we decided to move forward with "no license" (which effectively means copyrighted) until we come to a final decision.  It is good that this issue exists as a reminder so we don't forget though!
