### ISSUE TITLE
eth_getTransactionCount doesn't support pending tag that Ethers' provider.populateTransaction() appears to use.

### ISSUE THREAD

**Issue by 0xjimmy** [DarkFlorist/TheInterceptor#141]
eth_getTransactionCount doesn't support a tag that Ethers' provider.populateTransaction() uses.
It appears to use the tag ``"pending"`` where we only support at a block or ``"latest"``

https://github.com/DarkFlorist/TheInterceptor/blob/main/extension/app/ts/utils/wire-types.ts#L133

```ts
// Error from Ethers using provider.populateTransaction with missing nonce
{"code":400,"data":{"request":{"method":"eth_getTransactionCount","params":["0xba1c153449f72ad7a26ae5be97466316d61ce0ef","pending"]}},"name":"EthereumJsonRpcError"}
```

> For this I think we should just map requests of pending to latest, since our latest includes "queued" transactions.
@MicahZoltu

**Comment by KillariDev** [comment]
`pending` was added to blocktag
