### ISSUE TITLE
Brave - refused to execute inline script because it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by randomishwalk** [DarkFlorist/TheInterceptor#15]
Brave version: [Version 1.46.134 Chromium: 108.0.5359.94 (Official Build) (64-bit)](https://brave.com/latest/)

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-Pno6VqOVhlRXSd0eVB22rNathycbNhTyHseqef92DaU='), or a nonce ('nonce-...') is required to enable inline execution.

```html

<!DOCTYPE html>
<html>
	<head>
		<meta charset = 'utf-8'>
		<link rel = 'icon' type = 'image/x-icon' href = 'favicon.ico'>
	</head>
	<body style = 'width: 520px; height: 400px;'>
		<script async type = 'module' src = '../vendor/es-module-shims/es-module-shims.wasm.js'></script>
		<script type = 'importmap'>
		{
			"imports": {
				"ethers": "../vendor/ethers/ethers.esm.js",
				"webextension-polyfill": "../vendor/webextension-polyfill/browser-polyfill.js",
				"es-module-shims": "../vendor/es-module-shims/es-module-shims.js",
				"preact": "../vendor/preact/preact.module.js",
				"preact/jsx-runtime": "../vendor/preact/jsx-runtime/jsxRuntime.module.js",
				"preact/hooks": "../vendor/preact/hooks/hooks.module.js",
				"funtypes": "../vendor/funtypes/index.mjs",
				"node-fetch": "../vendor/node-fetch/index.mjs",
				"@zoltu/ethereum-abi-encoder": "../vendor/@zoltu/ethereum-abi-encoder/index.js",
				"@zoltu/ethereum-crypto": "../vendor/@zoltu/ethereum-crypto/index.js",
				"@zoltu/rlp-encoder": "../vendor/@zoltu/rlp-encoder/index.js",
				"@darkflorist/address-metadata": "../vendor/@darkflorist/address-metadata/index.js"
			}
		}
	</script>

		<main>Loading...</main>

		<script type = 'module' src = '../js/background/background.js'></script>
	</body>
</html>

```
![image](https://user-images.githubusercontent.com/94845277/205971006-85b79ffb-4596-442b-9aeb-4295f8ab4752.png)

**Comment by MicahZoltu** [comment]
I believe this is an ignorable error and should go away once Brave implements import maps.  We are using an importmap polyfill at the moment, and once Brave adds support it should automatically switch over to using built-in over the polyfill.

Going to leave this open until someone on the team can verify this, but we'll probably close it if my assertions above are correct.
