### ISSUE TITLE
refreshing the page still prompts me to approve access to my previous address, rather than the new address.

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/TheInterceptor#182]
Micah: Bug: When I switch addresses in MetaMask while Interceptor is in signing mode, refreshing the page still prompts me to approve access to my previous address, rather than the new address.

Micah: 1. Open a dapp with MM address A selected and Interceptor in signing mode.
2. Deny the prompt to allow the dapp to access address A.
3. Clear the denial.
4. Change MM address to B.
5. Refresh the page.
6. Notice that Interceptor prompts you to allow access to address A still.

Micah: Ah, it appears that Interceptor isn't noticing the address change in MetaMask.

**Comment by KillariDev** [comment]
unable to reproduce :/

**Comment by MicahZoltu** [comment]
Restarting Brave resolved the issue.  It may be valuable to continue tracking this for a bit in case it happens again.

**Comment by KillariDev** [comment]
seems like it did not reoccur, closing.
