### ISSUE TITLE
When asking if you want to connect a wallet, you should be able to say "yes, but not the one interceptor suggested".

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#24]
Essentially every time I get that pop-up I have the wrong wallet selected.  So I hit deny, then switch wallets and *hopefully* get another prompt. It would be much simpler if I just had an option to "enter an address" or if I was "using signer" if it told me "switch accounts in MetaMask and we'll prompt again" or something.

**Comment by KillariDev** [comment]
related to https://github.com/DarkFlorist/TheInterceptor/issues/46
