### ISSUE TITLE
Unsynchronized network when changing the selection in simulation mode then switching to signing mode

### ISSUE THREAD

**Issue by jubalm** [DarkFlorist/TheInterceptor#264]
Changing network in simulation mode then switching to signing mode causes the network between Interceptor and MetaMask to be unsynchronized. FWIW, refreshing the page seem to correct the active network shown in TheInterceptor

https://user-images.githubusercontent.com/1169838/227522653-f870d926-f079-4c7c-88d4-a10314699fe1.mp4

**Comment by jubalm** [comment]
Seems `chainChanged` is not dispatched in simulation mode.

https://user-images.githubusercontent.com/1169838/228728831-0d8f1f46-699d-4e01-87ee-4ca1f4e8b1d8.mp4

**Comment by KillariDev** [comment]
this should be fixed in PR: https://github.com/DarkFlorist/TheInterceptor/pull/280
