### ISSUE TITLE
Fix creating tabs like Address Book on *nix systems

### ISSUE THREAD

**Issue by 0xjimmy** [DarkFlorist/TheInterceptor#269]
https://github.com/DarkFlorist/TheInterceptor/pull/268

**Manifest V2**
From testing with Manifest v2 on Firefox opening the address book creates a tab at `/html/html/addressBook.html`
Changing `getHtmlFile` return for v2 urls from `return ./html/${file}.html` to return `/html/${file}.html` fixes the issue on Firefox linux and macos

**Manifest V3**
Fixed by awaiting the request to service worker before closing the tab, was race condition.

- [x] Fixed on *nix
- [ ] Do these changes work on Windows?

**Comment by KillariDev** [comment]
merged
