### ISSUE TITLE
why `getBalance` shows extra very small extra eth on top of get rich +200k eth

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/TheInterceptor#277]

**Comment by KillariDev** [comment]
![image](https://user-images.githubusercontent.com/13102010/228805703-092ba9fc-66ed-4def-a532-dca6cfda3a0b.png)
I fail to reproduce this

**Comment by MicahZoltu** [comment]
@epheph What address were you using when you ran into the bug?  Maybe that matters?

**Comment by epheph** [comment]
💀
https://etherscan.io/address/0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf
"0.000000000000003685 ETH"

**Comment by MicahZoltu** [comment]
Hmm, that doesn't match what we were seeing.  You think Etherscan was just lying when we tested the other day?
