### ISSUE TITLE
get rid of "@types/chrome": "0.0.218",

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/TheInterceptor#295]
We need to figure out how to get this type otherwise

```ts
await chrome.scripting.registerContentScripts([{ // we need to use `chrome` here instead of `browser` as `world: 'MAIN'` is not supported otherwise
			id: 'inpage',
			matches: ['file://*/*', 'http://*/*', 'https://*/*'],
			js: ['/inpage/js/inpage.js'],
			runAt: 'document_start',
			world: 'MAIN',
		} ])
```

**Comment by KillariDev** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64960

**Comment by MicahZoltu** [comment]
Could we create a wrapper function that had the correct type signature and then inside that cast `browser.scripting.registerContentScripts` to a function that takes in `RegisteredContentScriptOptions & { world?: ExecutionWorld | undefined }`?  Alternatively, if this is the only place that we are calling it, we could just do the cast inline with a comment above it about why.
