### ISSUE TITLE
Clicking one side of the Simulating/Signing toggle shouldn't toggle, but set.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#3]
If you click on the left side of the Simulating | Signing toggle, it will switch you to Simulating mode.  If you click in the same spot again it will switch you back to Signing.  Given the way we have this element designed, I think clicking on one side should set the state to that side, rather than toggle.  So to switch back to Signing you would need to click on the Signing side.

Alternatively, I think if we change the design so the words are outside of the toggle and the toggle is a UI element between them, then it would be more intuitive to have the toggle flip left/right with each click.

**Comment by KillariDev** [comment]
fixed
