### ISSUE TITLE
Swaps with multiple paths are not  detected as swaps

### ISSUE THREAD

**Issue by 0xjimmy** [DarkFlorist/TheInterceptor#317]
Multi-hop swaps are fine, like `ETH -> USDC -> DAI` detects a ETH to DAI swap.
But Uniswap can also create multiple swap paths to which are not detected, for example `ETH -> USDC -> DAI` + `ETH -> DAI`.

**Comment by KillariDev** [comment]
Hmm, they seem to be? Here's an example, do you have example case?
![image](https://user-images.githubusercontent.com/13102010/231100863-0962aa2d-2008-4447-8ffc-dddeea5b3abe.png)
![image](https://user-images.githubusercontent.com/13102010/231101053-1ceafe50-b970-4745-a051-be340aadb2a7.png)

**Comment by KillariDev** [comment]
ah right. The issue arises when your account receives multiple token batches, these should be grouped together
