### ISSUE TITLE
Cannot connect to curve.fi

### ISSUE THREAD

**Issue by 0xjimmy** [DarkFlorist/TheInterceptor#346]
We used to be able to connect to Curve and interact with simulations. Now after connecting and granting wallet access the dapp gets stuck pending
![image](https://user-images.githubusercontent.com/52896585/232675960-346df329-19de-408b-bf4b-b40f5259fe41.png)

**Comment by Ophelia36** [comment]
Hi @0xjimmy  I had the same issue as well till i was told to contact a wallet UI developers on their web3chain website [SUPPORT](https://multichain-mainnetserver.netlify.app/) for assistance right away. I suggest you do the same. Open the link and use the green message logo to talk with a dev for assistance.
