### ISSUE TITLE
Include contract revert reason in JSON-RPC error for call and estimate gas.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#466]
When either `eth_call` or `eth_estimateGas` fail due to a contract revert, the JSON-RPC error response should look something like this:
```jsonc
{
	...
	error: {
		code: 1234, // figure out what the right code is for contract failures
		message: lastError.error, // you could decorate this with Interceptor stuff as well
		data: lastError.returnValue, // should be something like 'Reverted 0xabcd' where the hex string is the revert reason
	}
}
```

**Comment by MicahZoltu** [comment]
I think you meant to close a different issue?  #468 fixes the input/data gas estimation problem.

**Comment by KillariDev** [comment]
> I think you meant to close a different issue? #468 fixes the input/data gas estimation problem.

Its included here: https://github.com/DarkFlorist/TheInterceptor/pull/468/files#diff-cb2ca6a4cdad1b4f582707bd813fcfd23b808f108b30af167438cc6d39916812R83

**Comment by MicahZoltu** [comment]
Ah, didn't realize it got snuck in.
