### ISSUE TITLE
Make intercepted metamask object indistinguishable from non-intercepted

### ISSUE THREAD

**Issue by epheph** [DarkFlorist/TheInterceptor#508]
It's difficult to determine what indistinguishable means. There are numerous ways say `eth_call` or even prodding for the get stack (used in bouquet)

**Comment by KillariDev** [comment]
instead of making "indistinguishable", make a metamask compatibility mode.
atleast these things need to be done:
window.ethereum needs to have active address in it
isMetamask is set to true
