### ISSUE TITLE
Test the extension more thoroughly with different dapps and report how well it works in each

### ISSUE THREAD

**Issue by epheph** [DarkFlorist/TheInterceptor#511]
Collect result in spreadsheet, publish on web site

**Comment by sambacha** [comment]
The problem with this is not knowing which version of said DApp the user is actually using. GitHub provides a deployments API or having DApps provide a build id hash or something to distinguish builds would be needed ideally.

Really perhaps a test dapp harness that used different frameworks (wagmi vs web3 react vs useDapp etc). may be easier to manage and less fragile.

**Comment by MicahZoltu** [comment]
Agreed, it would be great if dapps were deployed via IPFS and we could specify exact content hashes.  I think without that the best we can do **realistically** is to just re-evaluate a dapp if a user claims that our list is incorrect, and/or periodically run through all of the dapps to test for compatibility.

**Comment by sambacha** [comment]
> Agreed, it would be great if dapps were deployed via IPFS and we could specify exact content hashes.  I think without that the best we can do **realistically** is to just re-evaluate a dapp if a user claims that our list is incorrect, and/or periodically run through all of the dapps to test for compatibility.

I have used this for Sushis frontend https://chrome.google.com/webstore/detail/testim-editor/pebeiooilphfmbohdbhbomomkkoghoia

https://www.testim.io/playwright-recorder/

Basically lets you record a user interaction and replay it as a test. However these sorts of tools at best support you providing your own chrome binary (i.e. you can run a test for the extension on your local machine or whereever chrome and the extension have been setup). 

There is not really a great way of setting up chrome to test extensions not available yet on chrome store. 

For new DApps, what are the constraints as it relates to being completely compatible?

**Comment by MicahZoltu** [comment]
The primary constraint for working with Simulation Mode is that the dapp doesn't depend on any external services for Ethereum blockchain state/data.  For example, TheGraph, Infura, custom indexing server, etc..  The dapp **must** route all requests for blockchain state through the connected wallet for it to work with Interceptor's Simulation mode.  This includes all `eth_call`, `eth_balance`, `eth_estimateGas` calls, etc.
