### ISSUE TITLE
make too high gas price error to be dynamic

### ISSUE THREAD

**Issue by epheph** [DarkFlorist/TheInterceptor#512]
https://github.com/DarkFlorist/TheInterceptor/blob/9ce3769113b31aadb3191318ce6ea8c28d02ad18/app/ts/simulation/protectors/feeOops.ts#LL9C1-L9C1

(do dapps ever send gas price?)

**Comment by MicahZoltu** [comment]
BitPay used to, which completely broke integration with EIP-1559.  I think they finally fixed it though.  One could imagine an "ETH Sweeper" app that supplies a gas price as well.
