### ISSUE TITLE
Add Uniswap V3 (and other?) exchanges to token price estimator

### ISSUE THREAD

**Issue by epheph** [DarkFlorist/TheInterceptor#514]
https://github.com/DarkFlorist/TheInterceptor/blob/9ce3769113b31aadb3191318ce6ea8c28d02ad18/app/ts/simulation/priceEstimator.ts#L24

**Comment by epheph** [comment]
Consider deployed contract

**Comment by 0xjimmy** [comment]
Methods for calling fetching required data offchain and calculating prices / pool addresses.
https://gist.github.com/0xjimmy/0c0c99935088e678490b82b9bb046d8a

Spot prices as well as quotes, quotes include market slippage based on the amount traded.

Calculates and optimistically calls the 5 possible LP pools (v2 + the 4 v3 variants) with multicall, if they revert then we know the pool or liquidity does not exist,

**Comment by 0xjimmy** [comment]
For token balance changes, we would only want to use spot prices, but for custom Uniswap cards the quotes are useful when parsing swap calls to determine what % slippage the user has agreed to - can warn if it appears to be large slippage allowance.
