### ISSUE TITLE
Arrow bounces when window is resized

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/TheInterceptor#52]
![image](https://user-images.githubusercontent.com/13102010/207903750-4f059f7a-8273-491a-8196-ea21e25eec40.png)

**Comment by DecentralisedTech** [comment]
Was not able to reproduce in both Firefox and Brave. Is this still an issue with the arrow?
The resizing of the inner light grey card could be replaced with some flex positioning though.

**Comment by KillariDev** [comment]
yah, seems like that is no longer issue. But the container is limited by some max size, I guess this is what you mean by the flex positioning?

**Comment by DecentralisedTech** [comment]
Yes exactly
