### ISSUE TITLE
logsBloom should be null for pending block

### ISSUE THREAD

**Issue by sambacha** [DarkFlorist/TheInterceptor#522]
https://github.com/DarkFlorist/TheInterceptor/blob/9ce3769113b31aadb3191318ce6ea8c28d02ad18/app/ts/simulation/services/SimulationModeEthereumClientService.ts#LL381C5-L381C50

 `logsBloom` is expected to be null for pending block

**Comment by MicahZoltu** [comment]
This isn't technically a pending block, it is a "new head that will be reorged out shortly".  Ideally, we would properly calculate the bloom filter for the block, which we have all of the information necessary to do, but that requires a bunch of effort.
