### ISSUE TITLE
show how much gas is left in simulation. Currently simulator is restricted by the gas limit, so we could show it to user

### ISSUE THREAD

**Issue by epheph** [DarkFlorist/TheInterceptor#529]
Copied from prior tracking. Not sure what this means. How much gas is left vs what? Block gas limit? Each TX?

**Comment by MicahZoltu** [comment]
Our multicall is limited to a single block gas limit.  New multicall won't have such a limit so my guess is we won't fix this.

**Comment by epheph** [comment]
Seems a pretty unusual case hitting 30m anyway. closing
