### ISSUE TITLE
Investigate intercepting metamask's rpc connection

### ISSUE THREAD

**Issue by epheph** [DarkFlorist/TheInterceptor#53]
Interceptor is able to intercept transaction requests that come from the dapp and check for various issues/simulate prior to sending off to metamask. However, after sending off to Metamask, the user can make a mistake with the gas price (especially when replacing transaction). Additionally, to support bundles, the rpc provider must take the signed transaction and not forward it to the jsonrpc endpoint (instead, collecting multiple transactions, sending to private bundling relay like Flashbots relay).

Additionally, many users use Metamask to initiate transactions (and will often make mistakes related to destination, like sending to the contract address itself).

If we could add a jsonrpc proxy (listening on a real tcp port on the local machine) we could protect, simulate, and bundle transactions we otherwise would have no visibility. We could also get Metamask to participate in the "simulation stack" mode. "Make me rich" could ALSO make you rich in Metamask and would allow you to use Metamask to sign transactions that otherwise wouldn't be possible due to Metamask thinking you don't have enough ETH.

We could also allow Metamask to read RPC from one server, send transactions to another (or multiple) providers.

James found this: https://developer.chrome.com/docs/extensions/reference/sockets_tcpServer/

**Comment by epheph** [comment]
cc @DecentralisedTech

**Comment by DecentralisedTech** [comment]
Looks like sockets APIs got dropped in 2020. For catching RPC connections adding custom proxy networks to the users wallets makes sense as it will work with every wallet.

Since running a RPC server from the extension isn't an option I'd suggest running a server that users wallets and the interceptor connect to.
```md
Wallet <--[ Externally Hosted Server ]--> Intercepter <--> Network RPC
```

This isn't ideal because users are trusting the server with their signed transactions unless they self host.

**Comment by MicahZoltu** [comment]
That is the setup we are trying very hard to avoid.  We want our wallet to be the most privacy preserving wallet, which means we go to great lengths to avoid sending anything out to external servers.

There is no replacement to the sockets API after it was dropped?  They just dropped the ability to listen on a socket in any way entirely?

**Comment by DecentralisedTech** [comment]
I believe so. Their migrations page doesn't have any listed replacement for sockets (https://developer.chrome.com/docs/apps/migration/#sockets).

**Comment by epheph** [comment]
Talking with @DecentralisedTech , we wondered if any other non-metamask wallets would provide a signed transaction without propagating. Looking into WalletConnect, and the docs were misleading, but we discovered it could not sign without propagating.

**Comment by MicahZoltu** [comment]
We still need to canvas the ecosystem and come up with a list of all other wallets.  I think this is something that would help us evaluate if maybe there are some things (like this) we can do that just won't work with MM but will work with others.
