### ISSUE TITLE
figure out how to get rid of any's in inpage script

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/TheInterceptor#541]
The `as any` is unnecessary here if you are properly checking all possible paths.  Note: Make sure you are using a recent version of TypeScript as this sort of narrowing was added fairly recently.  It is worth noting that in the current code you aren't validating that `.data` is an object if it is present, so this could runtime fail if you have a string as the `data` property on an error.
```suggestion
				if (!('data' in error) || error.data === undefined || error.data === null) error.data = { request: forwardRequest }
				else if ( 'data' in error && !('request' in error.data)) error.data.request = forwardRequest
```
I wonder if we can use funtypes to do this in a cleaner way?  Where `ErrorWithDataAndRequest` is defined as `{ data?: { request?: {} } }`?  Then we could do something like:
```ts
const result = ErrorWithDataAndRequset.safeParse(error)
if (result.success) {
	result.value.data = result.value.data || {}
	result.value.data!.request = result.value.data!.request || forwardRequest
}
```

_Originally posted by @MicahZoltu in https://github.com/DarkFlorist/TheInterceptor/pull/539#discussion_r1237880141_

**Comment by MicahZoltu** [comment]
Note: This way has the benefit of handling a non-object `data` gracefully compared to other options.

**Comment by KillariDev** [comment]
fixed
