### ISSUE TITLE
Incognito tabs do not get injected ``window.ethereum``

### ISSUE THREAD

**Issue by 0xjimmy** [DarkFlorist/TheInterceptor#548]
Incognito tabs do not get injected ``window.ethereum`` when the extension is enabled to run in incognito mode.
Tested only on chromium, so do not know if it is the same for Firefox also.

**Comment by KillariDev** [comment]
![image](https://github.com/DarkFlorist/TheInterceptor/assets/13102010/5a2ec748-b883-478d-9d7a-83dbefc66788)
I fail to reproduce on Chrome

**Comment by KillariDev** [comment]
seems to work on firefox too:
![image](https://github.com/DarkFlorist/TheInterceptor/assets/13102010/238b527f-1c7a-49ac-867d-1d20ef92595a)

**Comment by KillariDev** [comment]
nothing to fix

**Comment by KillariDev** [comment]
nothing to fix
