### ISSUE TITLE
Class instances, especially native ones, aren't simple objects.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#549]
https://github.com/DarkFlorist/TheInterceptor/blob/18c51b57261ae42a5b7a35a8808ad8326cc141a2/app/inpage/ts/inpage.ts#L189-L197

```ts
var a = { ...new Error('hello') }
a.message === undefined // true
```

This code is throwing an object that contains some stuff that kinda looks like an error but is not an `instanceof Error` and doesn't have many fields that errors normally have like the stack trace, message, etc.  Instead, it should add a `code` and `data` property to the existing `error` and then throw that.

**Comment by KillariDev** [comment]
hmm, I felt it felt ugly if we just add new params to the error

**Comment by KillariDev** [comment]
I guess my issue here is that the throwable can be really anything, and I don't know how to handle all possible cases

**Comment by MicahZoltu** [comment]
I recommend writing a helper method that deals with all of this as it can quickly become complicated and it often is needed in multiple places.  If error.data exists and is an object, add a property to it, else add `data` as an object and nest existing `error.data` as a property in that object.  If error is not an Error, then wrap it in an Error and throw that.  etc.
