### ISSUE TITLE
Solidity Errors are not decoded or formatted

### ISSUE THREAD

**Issue by 0xjimmy** [DarkFlorist/TheInterceptor#556]
![image](https://github.com/DarkFlorist/TheInterceptor/assets/52896585/1156516f-ee30-4554-8fb4-86f420601959)
This is what I am assuming is a error for passing the deadline to swap.
```ts
error TransactionDeadlinePassed()
```
These errors are ABI encoded, so we cannot actually decode without an ABI. Would a list of common error functions or popular contracts be worth adding support for?

**Comment by KillariDev** [comment]
there's issue for uniswap ones: https://github.com/DarkFlorist/TheInterceptor/issues/439

but yeah, I feel we could add for popular contracts
