### ISSUE TITLE
Propogate gas estimation errors to dapp on rejection.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#565]
If a transaction errors during speculative execution the UI will warn that the transaction will likely fail and give you reject/accept options.  If you reject, the UI only gets this message, but no details about the transaction failure:
> Interceptor Tx Signature: User denied transaction signature.

If the user rejects a failing transaction, the UI should be told about the failing transaction rather than the user rejection.

**Comment by KillariDev** [comment]
hmm, I am not sure if we should be doing this, but I guess there's no standard for what errors should the `eth_sendTransaction` return in each case? Are other wallets show other errors than decline on users decline? I feel that if we don't return transaction decline, some dapps could break as they got some other error than was expected

**Comment by MicahZoltu** [comment]
I would be fairly surprised if there are any dapps out there that are looking *only* for rejection errors.  As long as we return an error, I think dapps will do the right thing.  The proposed change here is to just change the error type to include transaction failure details rather than saying "User denied transaction signature".
