### ISSUE TITLE
Active wallet not correct on bouquet upon importing payload from the interceptor

### ISSUE THREAD

**Issue by epheph** [DarkFlorist/TheInterceptor#568]
1. Wallet A and Wallet B is being used in the same browser
2. Initially tested with wallet A, connected to bouquet and initiated simulations without problem
3. Switched to wallet B, both in interceptor and bouquet
4. Simulated transaction with interceptor using wallet B with no problem. Proper address appears in the simulation stack ( in the extension)
5. Upon importing payload to bouquet, address being reflected on the stack on the bouquet is that of Wallet A instead of wallet B. Interceptor simulation stack still shows wallet B. Sometimes, pressing on importing payload again switches it to the correct wallet, wallet B

**Comment by KillariDev** [comment]
this is bouquet bug I think, but also something that could be fixed in the current master

**Comment by KillariDev** [comment]
does not occur anymore
