### ISSUE TITLE
funtypes preventing wallet_addEthereumChain from being passed through to metamask

### ISSUE THREAD

**Issue by epheph** [DarkFlorist/TheInterceptor#569]

**Comment by epheph** [comment]
https://www.flashbotsrpc.com/

for unknown methods, we should pass along to the wallet.

```
Uncaught (in promise) EthereumJsonRpcError: Unable to assign {method: "wallet_addEthereumChain" ... } to { readonly method: "eth_getBlockByNumber"; readonly params: [ParsedValue<string> | ParsedValue<string> | "latest" | "pending", boolean]; } | { readonly method: "eth_getBalance"; readonly params: [ParsedValue<string>, ParsedValue<string> | ParsedValue<string> | "latest" | "pending"]; } | { readonly method: "eth_estimateGas"; readonly params: [{ readonly from?: ParsedValue<string>; readonly gas?: ParsedValue<string>; readonly value?: ParsedValue<string>; readonly to?: ParsedValue<string> | null; readonly gasPrice?: ParsedValue<string>; readonly maxPriorityFeePerGas
```

**Comment by MicahZoltu** [comment]
In simulation mode, unknown methods should result in an error, but it should be more clear to the user than a funtype error.  e.g., "`wallet_addEthereumChain` is not supported by Interceptor."

In signing mode, I agree with @epheph that we should just forward the request to the underlying wallet.

**Comment by KillariDev** [comment]
hmm, I don't feel we should just blindly forward everything 🤔 . If you have a typo in method, it sounds silly that its just passed to wallet. Or if there's a new signing method that we don't support, you could bypass interceptor using that.

**Comment by MicahZoltu** [comment]
There will almost certainly be times when a wallet implements some new feature that we haven't integrated yet, and we don't want the solution for the user to be "disable Interceptor".  Perhaps we can let the user know about the unexpected request and ask the user if they want to pass the request on to the wallet (with a remember me button)?  We can give them a sufficient warning saying that we don't recommend clicking yes.
