### ISSUE TITLE
Doesn't work with peepeth.com

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#63]
1. Navigate to https://peepeth.com/a/login
2. Click "Sign in with Web3"
3. Note that you get an error saying you need to install MetaMask

**Comment by MicahZoltu** [comment]
It appears this is because peepeth is *very* old and is looking for `window.web3`!

```
ReferenceError: web3 is not defined
```

**Comment by KillariDev** [comment]
should we support this kind of stuff? there's also other deprecated stuff in metamask (like putting the address to `window.ethereum.selectedAddress`)

**Comment by MicahZoltu** [comment]
Good question.  I want to support good censorship resistance dapps, but you are right that we should probably focus our efforts on things that work using the latest tech and/or are very popular.

**Comment by KillariDev** [comment]
add support atleast for `eth_accounts`, `eth_coinbase`, `eth_uninstallFilter` and `net_version` for eth_send

**Comment by KillariDev** [comment]
peepeth is not up anymore, no need to add support

**Comment by MicahZoltu** [comment]
Site was just down, I mentioned it to them and they fixed it.
