### ISSUE TITLE
Gnosis Safe

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#72]
If I load https://app.safe.global/ with Interceptor but not MetaMask in Brave, I do not get an interceptor pop-up to connect.  If I add MetaMask and then refresh the page, I *then* get an Interceptor popup to connect.

My expectation is that when using interceptor with simulation only I would get a pop-up to connect just the same as if I have MM installed.

**Comment by MicahZoltu** [comment]
Tested on v0.0.8

**Comment by KillariDev** [comment]
They use internal MetaMask function `window.ethereum?._metamask?.isUnlocked?.()` to check if metamask is unlocked. They also have `isMetaMask` flag check. I think they should fix this in their application

https://github.com/safe-global/web-core/blob/ef0389a6eb3f4041e5abfb4d757042358222b64a/src/utils/wallets.ts#L32

**Comment by KillariDev** [comment]
I actually did not know about this api: https://docs.metamask.io/guide/ethereum-provider.html#experimental-methods

**Comment by DecentralisedTech** [comment]
#78

**Comment by MicahZoltu** [comment]
Ah, I see.  Looks like you can connect by just clicking the connect button in the app.  I'm satisfied with our current behavior, and I'm not a huge fan of implementing MetaMask specific functions when MM isn't present.
