### ISSUE TITLE
Add ability to easily rename a signer-connected address.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#73]
When connecting to a signer, I just get an address.  I wont to be able to easily name it rather than just having an address, but at the moment I have to copy it, go into my address book, create a new entry, paste in the address, give it a name, and then save.  Would much rather have a little edit button.

**Comment by KillariDev** [comment]
Currently there's faster flow, you can copypaste the address to interceptor window and it will prompt create new address view right away. But yeah, we should it to be faster for signer addresses.

We were discussing a way to add them automatically before. But I think this kind of prompting to add could be better

**Comment by KillariDev** [comment]
now you can rename addresses directly
