### ISSUE TITLE
Figure out better way to communicate between background page and popups

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/TheInterceptor#74]
Currently background page informs popups with `popup_` messages that some data is updated, and then popup retrieves the updated data via `await browser.runtime.getBackgroundPage()`. Is there some other ways of doing this communication instead of using `window.interceptor` global?

We could use these popup messages to tell what has changed when popups are open, but the popups also need to get their current state when the popup open. They cannot have persistent state on their own.

**Comment by jubalm** [comment]
just stumbled, could this be somewhat of use?
https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API

**Comment by KillariDev** [comment]
fixed with normal messaging
