### ISSUE TITLE
Start discussion on redesign

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/TheInterceptor#772]
[Figma Link](https://www.figma.com/file/JAhOVsNfaZkXf8sJ6g3eCa/TheInterceptor-Redesign?type=design&node-id=14%3A508&mode=design&t=C0rS6HQ1OiNETR27-1)

**Comment by jubalm** [comment]
Started the discussion here

https://github.com/DarkFlorist/TheInterceptor/discussions/788
