### ISSUE TITLE
EIP-712 handling of JSON arrays is broken.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#773]
![image](https://github.com/DarkFlorist/TheInterceptor/assets/886059/3f5f4f95-a026-4189-90da-539097cd2e96)

Note how the array is presented as an object with number keys.  Such fields like this should be presented as hex strings if possible, or at least array of numbers if not.

**Comment by KillariDev** [comment]
I couldn't find example case to reproduce
