### ISSUE TITLE
When MetaMask locks while Interceptor is reviewing a transaction, sending to signer just sends to /dev/null.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#810]
1. Install Interceptor.
2. Install MetaMask.
3. Configure MetaMask to have a short idle timeout.
4. Initiate a transaction on some dapp so Interceptor pops up the signing window.
5. Wait for MetaMask to idle timeout.
6. Click button in Interceptor to send transaction to signer.
7. Notice that the Interceptor window closes and the MetaMask doesn't pop-up.

**Comment by KillariDev** [comment]
fixed in https://github.com/DarkFlorist/TheInterceptor/pull/876
