### ISSUE TITLE
Bug: Erroneous error about attempting to send to something in address book.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#814]
![image](https://github.com/DarkFlorist/TheInterceptor/assets/886059/69d5b59b-1537-49de-81ed-c0125c10a7b1)

Contract wallet recipient is in my address book, but Interceptor complains that it is not.

**Comment by KillariDev** [comment]
this is 0.76? The recipient is EOA and as "contact" in interceptor? I thought I fixed this issue
