### ISSUE TITLE
v, s, r and yParity to 0 for simulated transactions (instead o signing with 0x1)

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/TheInterceptor#84]
set signature values v, s, r and yParity to 0 for simulated transactions:
"v": "0x0"
"s": "0x0"
"r": "0x0"
"yParity": "0x0"

Check also that signature retrieval should fail for these

**Comment by MicahZoltu** [comment]
If you can `ecrecover` with all zero values, then we should change them to `2^256-1` which I am quite confident are invalid `r` and `s` values.  (v/yParity should still be `0` as those are one bit/byte).
